config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles 
  resources :users 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord 
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :find_article, only: [:show, :edit, :update, :destroy]
  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new 
  end

  def create
    @article = Article.new(article_params)
    @article.save!
    redirect_to articles_path
  end

  def edit 
  end

  def update
    @article.update(article_params) 
    
    redirect_to article_path(@article)
  end
  
  def destroy
    @article.destroy
    redirect_to article_path
  end

  private

  def find_article
    @article = Article.find_by_id(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :description, :user_id)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def show
  end

  def new
    @user = User.new 
  end

  def create
    @user = User.new(user_params)
    @user.save 
    redirect_to users_path
  end

  def edit 
  end

  def update
    @user.update(user_params) 
    
    redirect_to user_path(@user)
  end
  
  def destroy
    @user.destroy
    redirect_to users_path
  end

  private

  def find_user
    @user = User.find_by_id(params[:id])
  end

  def user_params
    params.require(:user).permit(:name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: @article) do |article| %>

  <h3>Title </h3>
  <p><%= article.text_field :title %></p>

  <h3>Desc</h3>
  <p><%= article.text_field :description %></p>
  
  <h3> User </h3>

  <p><%= article.collection_select :user_id, User.all, :id, :name %> </p>
  <p><%= article.submit  %> </p>

<% end %>

app/views/articles/edit.html.erb
<h1>Edit Article</h1>
<%= render "form" %>

<%= link_to "Cancel or Return", articles_path  %>

app/views/articles/index.html.erb
<h1>Articles Information </h1>
<%= link_to "Create New Person", new_article_path %>
<%= link_to "Create New User", new_user_path %>

<% @articles.each do |art| %>

<p>Title: <%= art.title %> 
<p>Description: <%= art.description %> 
<%= link_to "Show", article_path(art)  %> 
<%= link_to "Edit", edit_article_path(art) %>
<%= link_to "delete", article_path(art) , data: {turbo_method: :delete, turbo_confirm: "Are you sure want to delete ?"} %>
<% end %>

app/views/articles/new.html.erb
<h1>Create Article</h1>
<%= render "form" %>

<%= link_to "Cancel or Return", articles_path  %>

app/views/articles/show.html.erb
<h1> Article Information </h1>

<p>Title <%= @article.title %> </p>
<p>Description <%= @article.description%> </p>
<p>Create By: <%= @article.user.name%> </p>


<%= link_to "return", articles_path  %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssociationGuide</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: @user) do |user| %>

  <h3>Title </h3>
  <p><%= user.text_field :name %></p>
  
  <p><%= user.submit  %> </p>

<% end %>

app/views/users/edit.html.erb
<h1>Edit user</h1>
<%= render "form" %>

<%= link_to "Cancel or Return", users_path  %>

app/views/users/index.html.erb
<h1>Users </h1>
<%= link_to "Create New User", new_user_path %>
<% @users.each do |user| %>

<p>Name: <%= user.name %> 
<%= link_to "Show", user_path(user)  %> 
<%= link_to "Edit", edit_user_path(user) %>
<%= link_to "delete", user_path(user) , data: {turbo_method: :delete, turbo_confirm: "Are you sure want to delete ?"} %>
<% end %>

app/views/users/new.html.erb
<h1>Create user</h1>

<%= render "form" %>

<%= link_to "Cancel or Return", users_path  %>

app/views/users/show.html.erb
<h1> Article Information </h1>

<p>Title <%= @user.name %> </p>

<%= link_to "return", users_path  %>